Implement parallel unpacking of source archives

diff --git a/install/deb/debian/rules b/install/deb/debian/rules
--- a/install/deb/debian/rules
+++ b/install/deb/debian/rules
@@ -30,24 +30,21 @@ override_dh_auto_configure:
 	dh_lintian
 
 extract_archive = \
-	if [ ! -f "$1" ]; then \
-		echo "Error: $2.tar.gz archive not found in ${SOURCE_PATH}"; \
-		exit 1; \
-	fi; \
-	tar -xf "$1" $3 --transform='s,^[^/]\+,$2,'
+	[ -f "$1" ] || { echo "Error: $2.tar.gz archive not found in ${SOURCE_PATH}"; exit 1; }; tar -xf "$1" $3 --transform='s,^[^/]\+,$2,'
 
 .PHONY: check_archives
 
 check_archives:
-	@echo "Checking for archives in sources directories..."
-	mkdir -p ${BUILD_PATH}
-	@$(call extract_archive,${SOURCE_PATH}/buildtools.tar.gz,buildtools,-C ${BUILD_PATH})
-	@$(call extract_archive,${SOURCE_PATH}/server.tar.gz,server,-C ${BUILD_PATH})
-	@$(call extract_archive,${SOURCE_PATH}/client.tar.gz,client,-C ${BUILD_PATH})
-	@$(call extract_archive,${SOURCE_PATH}/DocStore.tar.gz,DocStore,-C ${SERVER_PATH}/products/ASC.Files/Server)
-	@$(call extract_archive,${SOURCE_PATH}/campaigns.tar.gz,campaigns,-C ${BUILD_PATH})
-	@$(call extract_archive,${SOURCE_PATH}/plugins.tar.gz,plugins,-C ${BUILD_PATH})
-	@echo "Source archives check passed."
+	@echo "Checking for archives in sources directories..."; \
+	mkdir -p ${BUILD_PATH}; \
+	$(call extract_archive,${SOURCE_PATH}/buildtools.tar.gz,buildtools,-C ${BUILD_PATH}) & \
+	$(call extract_archive,${SOURCE_PATH}/server.tar.gz,server,-C ${BUILD_PATH}) & \
+	$(call extract_archive,${SOURCE_PATH}/client.tar.gz,client,-C ${BUILD_PATH}) & \
+	$(call extract_archive,${SOURCE_PATH}/campaigns.tar.gz,campaigns,-C ${BUILD_PATH}) & \
+	$(call extract_archive,${SOURCE_PATH}/plugins.tar.gz,plugins,-C ${BUILD_PATH}) & \
+	wait; \
+	$(call extract_archive,${SOURCE_PATH}/DocStore.tar.gz,DocStore,-C ${SERVER_PATH}/products/ASC.Files/Server}); \
+	echo "Source archives check passed."
 
 override_dh_auto_build: check_archives
 	cd ${BUILDTOOLS_PATH}/install/common/systemd; \
