fix Bug 77575 - Add health-based check for certificate trust

diff --git a/install/docker/config/docspace-ssl-setup b/install/docker/config/docspace-ssl-setup
--- a/install/docker/config/docspace-ssl-setup
+++ b/install/docker/config/docspace-ssl-setup
@@ -234,19 +234,20 @@ if [ -f "${CERTIFICATE_FILE}" ]; then
       create_renew_script
     else
       CONTAINER_NAME=$(docker ps --format '{{.Image}} {{.Names}}' | grep "docspace-api:" | awk '{print $2}')
+      CONTAINER_STATUS=$([ -n "$CONTAINER_NAME" ] && docker inspect -f '{{.State.Health.Status}}' "$CONTAINER_NAME" 2>/dev/null)
       TEMP_PATH="/tmp/$(basename "${CERTIFICATE_FILE}")"
 
       # Checking whether the certificate chain is trusted
-      if [ -n "$CONTAINER_NAME" ]; then
-        docker cp "${CERTIFICATE_FILE}" "${CONTAINER_NAME}:${TEMP_PATH}" >/dev/null 2>&1
+      if [ "$CONTAINER_STATUS" = "healty" ]; then
+        docker cp "$(readlink -f "${CERTIFICATE_FILE}")" "${CONTAINER_NAME}:${TEMP_PATH}" >/dev/null
         echo -n "Checking certificate trust inside ${CONTAINER_NAME}... "
-        docker exec "${CONTAINER_NAME}" openssl verify -CAfile /etc/ssl/certs/ca-certificates.crt \
-          -untrusted "${TEMP_PATH}" "${TEMP_PATH}" >/dev/null 2>&1 && echo "true" && CERT_TRUST_REQUIRED=false || echo "false" && CERT_TRUST_REQUIRED=true
-        docker exec "${CONTAINER_NAME}" rm -f "${TEMP_PATH}" >/dev/null 2>&1
+        docker exec "${CONTAINER_NAME}" openssl verify -CAfile /etc/ssl/certs/ca-certificates.crt -untrusted "${TEMP_PATH}" "${TEMP_PATH}" >/dev/null \
+          && { echo "true"; CERT_TRUST_REQUIRED=false; } || { echo "false"; CERT_TRUST_REQUIRED=true; }
+        docker exec "${CONTAINER_NAME}" rm -f "${TEMP_PATH}" >/dev/null
       else
         echo -n "Checking certificate trust on host... "
-        openssl verify -CAfile /etc/ssl/certs/ca-certificates.crt -untrusted "${CERTIFICATE_FILE}" "${CERTIFICATE_FILE}" >/dev/null 2>&1 \
-          && echo "true" && CERT_TRUST_REQUIRED=false || echo "false" && CERT_TRUST_REQUIRED=true
+        openssl verify -CAfile /etc/ssl/certs/ca-certificates.crt -untrusted "${CERTIFICATE_FILE}" "${CERTIFICATE_FILE}" >/dev/null \
+          && { echo "true"; CERT_TRUST_REQUIRED=false; } || { echo "false"; CERT_TRUST_REQUIRED=true; }
       fi
 
       if [ "$CERT_TRUST_REQUIRED" = true ]; then
