Improve cron handling in docspace-ssl-setup

diff --git a/install/common/product-ssl-setup b/install/common/product-ssl-setup
--- a/install/common/product-ssl-setup
+++ b/install/common/product-ssl-setup
@@ -160,20 +160,26 @@ if [ -f "${CERTIFICATE_FILE}" ]; then
     sed -i "s~\(ssl_dhparam \).*;~\1${DHPARAM_PATH};~g" ${OPENRESTY}/onlyoffice-proxy.conf
 
     if [[ "${LETSENCRYPT_ENABLE}" = "true" ]]; then
-      # Create and set permissions for ${PRODUCT}-renew-letsencrypt
-      echo '#!/bin/bash' > ${DIR}/${PRODUCT}-renew-letsencrypt
-      echo "certbot renew >> /var/log/le-renew.log" >> ${DIR}/${PRODUCT}-renew-letsencrypt
-      if [ $(pgrep -x ""systemd"" | wc -l) -gt 0 ]; then
-        echo 'systemctl reload openresty' >> ${DIR}/${PRODUCT}-renew-letsencrypt
-      else 
-        echo 'service openresty reload' >> ${DIR}/${PRODUCT}-renew-letsencrypt
-      fi
-
-      chmod a+x ${DIR}/${PRODUCT}-renew-letsencrypt
-
-      # Add cron job if /etc/cron.d directory exists
-      if [ -d /etc/cron.d ]; then
-        echo -e "@weekly root ${DIR}/${PRODUCT}-renew-letsencrypt" | tee /etc/cron.d/${PRODUCT}-letsencrypt
+      CRON_PATH=$(command -v crond || command -v cron) && CRON_SVC=${CRON_PATH##*/} || { echo "Error: neither crond nor cron is installed." >&2; }
+      if [[ -n "${CRON_SVC}" ]]; then
+        command -v systemctl &>/dev/null && systemctl enable --now "$CRON_SVC" || { command -v service &>/dev/null && service "${CRON_SVC%.service}" start; }
+        if [ -d /etc/cron.weekly ]; then
+            CRON_FILE="/etc/cron.weekly/${PRODUCT}-renew-letsencrypt"
+            echo '#!/bin/bash' > ${CRON_FILE}
+            echo '#' >> ${CRON_FILE}
+            echo "# ${PRODUCT} Renew Let's Encrypt SSL Certificates" >> ${CRON_FILE}
+            echo "" >> ${CRON_FILE}
+            echo "echo \"[\$(date '+%F %T')] START /etc/cron.weekly/${PRODUCT}-renew-letsencrypt\" >> \"/var/log/${PRODUCT}-renew-letsencrypt.log\"" >> ${CRON_FILE}
+            echo "certbot renew 2>&1 | tee -a /var/log/${PRODUCT}-renew-letsencrypt.log" >> ${CRON_FILE}
+            if [ $(pgrep -x ""systemd"" | wc -l) -gt 0 ]; then
+              echo 'systemctl reload openresty' >> ${DIR}/${PRODUCT}-renew-letsencrypt
+            else 
+              echo 'service openresty reload' >> ${DIR}/${PRODUCT}-renew-letsencrypt
+            fi
+            chmod a+x "${CRON_FILE}"
+        else
+          echo "Error: directory /etc/cron.weekly does not exist." >&2
+        fi
       fi
     else
       CERTIFICATE_SUBJECT=$(openssl x509 -subject -noout -in "${CERTIFICATE_FILE}" | sed 's/subject=//')
