Make minor changes to build_packages.yml

diff --git a/.github/workflows/build_packages.yml b/.github/workflows/build_packages.yml
--- a/.github/workflows/build_packages.yml
+++ b/.github/workflows/build_packages.yml
@@ -49,7 +49,7 @@ jobs:
     runs-on: ubuntu-latest
     outputs:
       matrix: ${{ steps.set-matrix.outputs.matrix }}
-      build_all: ${{ steps.changes.outputs.build_all }}
+      build_all: ${{ steps.set-matrix.outputs.build_all }}
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -61,19 +61,18 @@ jobs:
         run: |
           package_types=()
           if [[ "${{ github.event_name }}" == "push" ]]; then
-            package_types=("deb" "rpm")
+            package_types=("deb" "rpm"); echo "build_all=true" >> $GITHUB_OUTPUT
           else
             [[ "${{ github.event.inputs.deb_build }}" == "true" ]] && package_types+=("deb")
             [[ "${{ github.event.inputs.rpm_build }}" == "true" ]] && package_types+=("rpm")
           fi
-          [[ ${#package_types[@]} -eq 0 ]] && { echo "matrix=[]" >> "$GITHUB_OUTPUT"; exit 0; }
+          [[ ${#package_types[@]} -eq 0 ]] && { echo "::error::No package types specified"; exit 1; }
           matrix=$(printf '%s\n' "${package_types[@]}" | jq -R . | jq -sc '{include: map({packageType: .})}')
           echo "matrix=$matrix" >> $GITHUB_OUTPUT  
   build:
     name: Build Packages
     needs: prepare
     runs-on: ubuntu-22.04
-    if: ${{ fromJson(needs.prepare.outputs.matrix).length > 0 }}
     strategy:
       matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}
     steps:
