Test refactoring common scripts

diff --git a/.github/workflows/build_packages.yml b/.github/workflows/build_packages.yml
--- a/.github/workflows/build_packages.yml
+++ b/.github/workflows/build_packages.yml
@@ -6,6 +6,7 @@ on:
       - 'release/**'
       - 'hotfix/**'
       - 'develop'
+      - 'feature/fix-common-scripts'
     paths:
       - '.github/workflows/build_packages.yml'
   workflow_dispatch:
@@ -25,11 +26,11 @@ on:
       deb_build:
         description: 'Trigger DEB build'
         required: false
-        default: 'false'
+        default: 'true'
       rpm_build:
         description: 'Trigger RPM build'
         required: false
-        default: 'false'
+        default: 'true'
 
 concurrency:
   group: ${{ github.ref }}
@@ -40,9 +41,9 @@ env:
   PRODUCT_LOW: "docspace"
   BUILD_NUMBER: ${{ github.run_number }}
   PACKAGE_DIRECTORY: "/home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}"
-  BRANCH_BUILDTOOLS: ${{ github.event.inputs.branch-buildtools != '' && github.event.inputs.branch-buildtools || github.ref_name || 'develop' }}
-  BRANCH_CLIENT: ${{ github.event.inputs.branch-client != '' && github.event.inputs.branch-client || github.ref_name || 'develop' }}
-  BRANCH_SERVER: ${{ github.event.inputs.branch-server != '' && github.event.inputs.branch-server || github.ref_name || 'develop' }}
+  BRANCH_BUILDTOOLS: 'feature/fix-common-scripts'
+  BRANCH_CLIENT: 'develop'
+  BRANCH_SERVER: 'develop'
 
 jobs:
   prepare:
@@ -88,6 +89,13 @@ jobs:
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
+      
+      - name: "Checking common scripts for errors"
+        run: |
+          set -eux
+          sudo apt-get install -y shellcheck
+          find install/common -type f -name "*.sh" | xargs shellcheck --exclude="$(awk '!/^#|^$/ {print $1}' tests/lint/sc_ignore | paste -sd ",")" --severity=warning | tee sc_output
+          awk '/\(warning\):/ {w++} /\(error\):/ {e++} END {if (w+e) printf "::warning ::ShellCheck detected %d warnings and %d errors\n", w+0, e+0}' sc_output
 
       - name: Set product version
         run: |
